package com.javaninjas.careerpathway.quiz;

import com.javaninjas.careerpathway.quiz.model.Question;
import com.javaninjas.careerpathway.quiz.model.QuizResult;
import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

public class QuizServiceTest {
    @Test
    void testCalculateResultIsReproducible() {
        List<List<Question>> sets = QuizData.getQuizQuestionSets();
        QuizService service = new QuizService(sets);
        // Simulate answers: all "Very much" (index 4)
        List<Integer> answers = Arrays.asList(4,4,4,4,4, 4,4,4,4,4, 4,4,4,4,4, 4,4,4,4,4);
        QuizResult result1 = service.calculateResult(answers);
        QuizResult result2 = service.calculateResult(answers);
        assertEquals(result1, result2, "Quiz results should be reproducible for same input");
    }

    // test for getQuestionSet
    @Test
    void testGetQuestionSet() {
        List<List<Question>> sets = QuizData.getQuizQuestionSets();
        QuizService service = new QuizService(sets);
        List<Question> set0 = service.getQuestionSet(0);
        assertNotNull(set0, "Question set 0 should not be null");
        assertEquals(5, set0.size(), "Question set 0 should contain 5 questions");
    }

    //test for invalid index
    @Test
    void testGetQuestionSetInvalidIndex() {
        List<List<Question>> sets = QuizData.getQuizQuestionSets();
        QuizService service = new QuizService(sets);
        assertThrows(IndexOutOfBoundsException.class, () -> {
            service.getQuestionSet(10); // Assuming we have less than 10 sets
        }, "Accessing an invalid question set index should throw IndexOutOfBoundsException");
    }

    // Test that QuizData has at least one set of questions
    @Test
    void testQuizDataHasSets() {
        List<List<Question>> sets = QuizData.getQuizQuestionSets();
        assertFalse(sets.isEmpty(), "QuizData should contain at least one set of questions");
    }

    // Test that each question set has at least one question
    @Test
    void testRecordAutoGeneratedMethods() {
        Question q1 = new Question("Q1?", List.of("A", "B"));
        Question q2 = new Question("Q1?", List.of("A", "B"));
        assertEquals(q1, q2, "Records with same data should be equal");
        assertEquals(q1.hashCode(), q2.hashCode());
        assertTrue(q1.toString().contains("Q1?"));
    }
    
    // Tests for Question record validation
    @Test
    void testOptionsCannotBeNull() {
        assertThrows(IllegalArgumentException.class, () -> {
            new Question("Null options?", null);
        });
    }

    // test for less than 2 options
    @Test
    void testQuestionMustHaveAtLeastTwoOptions() {
        Exception ex = assertThrows(IllegalArgumentException.class, () -> {
            new Question("Invalid?", List.of("Only one option"));
        });
        assertEquals("Need at least 2 options.", ex.getMessage());
    }

    // test for valid question creation
    @Test
    void testValidQuestion() {
        Question q = new Question("Do you like coding?", List.of("Yes", "No"));
        assertEquals("Do you like coding?", q.prompt());
        assertEquals(2, q.options().size());
    }

    
}


